### ISSUE TITLE
Which libraries are needed / How to compile?

### ISSUE THREAD

**Issue by smmadge** [ketor/ceph-dokan#1]
Hi,

I can't get it to compile... Which sources from where do i need? I have tried to compile with windows libraries from mingw32msvc and from wine 1-6 but they error out during compilation :-(

Regards, Stan

**Comment by aisrael** [comment]
I was able to get this to compile using just [mingw](http://www.mingw.org/), [boost 1.57.0](http://www.boost.org/users/history/version_1_57_0.html) and [pthreads 2.9.1](https://www.sourceware.org/pthreads-win32/), but I had to make some edits to the Makefile.

I suppose you could also just copy the required libraries & headers under the mingw directories but I opted to keep them in their own directories.

**Comment by smmadge** [comment]
Thanks! Ketor already emailed me the details.
