### ISSUE TITLE
cannot mount 

### ISSUE THREAD

**Issue by richman1000000** [ketor/ceph-dokan#24]
Hi!
I'm trying to setup windows. and have failed mount

command results in error
C:\ProgramData\ceph>ceph-dokan  --cluster ceph01 -c c:\ProgramData\ceph\ceph01.conf -l -x
or 

C:\ProgramData\ceph>ceph-dokan  -c c:\ProgramData\ceph\ceph01.conf -l -x
```
unable to get monitor info from DNS SRV with service name: ceph-mon
2024-07-05T03:57:20.150-0700 1 -1 monclient: get_monmap_and_config cannot identify monitors to contact
failed to fetch mon config (--no-mon-config to skip)
```

file ceph01.conf

```
[global]
fsid = 933808ac-63d6-4542-8684-e606eb82ea19
mon_initial_members = ed-v-ceph01mon-01
mon_dns_srv_name = ceph01-mon
auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx
auth_supported = cephx

```
the rest of cluster functions normally.

**Comment by richman1000000** [comment]
Ceph version    18.2.2 reef (stable)

**Comment by ketor** [comment]
Sorry, this project can only support 0.94 version of ceph, and does not support authx.
Please check for official ceph project. Thanks!
