### ISSUE TITLE
No cephx support

### ISSUE THREAD

**Issue by wuxingyi** [ketor/ceph-dokan#5]
Hi,
    I had ceph-dokan compiled and the copied the ceph.conf to windows, but the command line just kept throwing "ceph_mount error!", what did i miss?
    please give me some hint~

**Comment by TelanJ** [comment]
Good day Wuxingyi,

Try changing the drive letter.
i.e.
"ceph-dokan.exe -c ceph.conf -l k"

Regards,
Julio Telan

On Tue, Mar 24, 2015 at 9:23 AM, wuxingyi notifications@github.com wrote:

> Hi,
> I had ceph-dokan compiled and the copied the ceph.conf to windows, but the
> command line just kept throwing "ceph_mount error!", what did i miss?
> please give me some hint~
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ketor/ceph-dokan/issues/5.

## 

 http://www.dlsu.edu.ph https://www.facebook.com/DLSU.Manila.100 
http://instagram.com/dlsu https://twitter.com/dlsumanila 
http://dlsumanila.tumblr.com/ http://iblog.lasalle.ph/

DISCLAIMER AND CONFIDENTIALITY NOTICE 
The information contained in this e-mail, including those in its 
attachments, is confidential and intended only for the person(s) or 
entity(ies) to which it is addressed. If you are not an intended recipient, 
you must not read, copy, store, disclose, distribute this message, or act 
in reliance upon the information contained in it. If you received this 
e-mail in error, please contact the sender and delete the material from any 
computer or system. Any views expressed in this message are those of the 
individual sender and may not necessarily reflect the views of De La Salle 
University.

**Comment by wuxingyi** [comment]
After debugging it using gdb, I found the error is caused by CEPHX auth. Then I modified the auth method to NONE, and FUSE is mounted happily.
My question is, is there any plan to support CEPHX auth?

**Comment by TelanJ** [comment]
This is what Ketor and I have been working on. The activation of Cephx for
the client

On Tue, Mar 24, 2015 at 11:42 AM, wuxingyi notifications@github.com wrote:

> After debugging it using gdb, I found the error is caused by CEPHX auth.
> Then I modified the auth method to NONE, and FUSE is mounted happily.
> My question is, is there any plan to support CEPHX auth?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ketor/ceph-dokan/issues/5#issuecomment-85329050.

## 

 http://www.dlsu.edu.ph https://www.facebook.com/DLSU.Manila.100 
http://instagram.com/dlsu https://twitter.com/dlsumanila 
http://dlsumanila.tumblr.com/ http://iblog.lasalle.ph/

DISCLAIMER AND CONFIDENTIALITY NOTICE 
The information contained in this e-mail, including those in its 
attachments, is confidential and intended only for the person(s) or 
entity(ies) to which it is addressed. If you are not an intended recipient, 
you must not read, copy, store, disclose, distribute this message, or act 
in reliance upon the information contained in it. If you received this 
e-mail in error, please contact the sender and delete the material from any 
computer or system. Any views expressed in this message are those of the 
individual sender and may not necessarily reflect the views of De La Salle 
University.

**Comment by wuxingyi** [comment]
That's really cool :)

**Comment by ketor** [comment]
Hi wuxingyi,
     I have update ceph-dokan to 0.93 (Hammer).
     In the next weeks i will try to add cephx auth to ceph-dokan. Please
just wait a moment.

Thanks.

**Comment by Beckham007** [comment]
hi, ketor. any new progress about cephx?

**Comment by TelanJ** [comment]
hi ketor, I was able to make the cephx work in our Rados.dll, If you like you can analyse it. https://github.com/AcalephStorage/ceph/tree/wip-rados_dll_cephx_authentication_hammer. I used Nss library which is readily available in windows

**Comment by ketor** [comment]
Hi @TelanJ ,thanks! It looks realy cool
I will look for your cephx code and try to port into ceph-dokan.

**Comment by TelanJ** [comment]
hi @ketor , Sorry I can't port the cephx code to your ceph-dokan because I've got a lot in my plate but if you want you can just `diff` the our source code from yours. It changed only a handful of files so I think It would only take you a week or two to finish it.

**Comment by ketor** [comment]
Hi @TelanJ , I can't find which commit you add cephx in your project.
Please help to point out the commits you add cephx.

**Comment by TelanJ** [comment]
@ketor The entire branch is dedicated to making the cephx work in the windows environment. I would suggest you just diff the source files to see what changed because the commits are still a bit unclean and I haven't got much time to squash the commits

**Comment by m-messiah** [comment]
Hello, @ketor , do you have any progress with cephx support?

**Comment by yogetter** [comment]
Hello, is 0.94.2 support cephfx now ? 
I still get error message "cephx server client.admin:  unexpected key: req.key=0" on my mon server.

**Comment by pivusan** [comment]
Hello, 
Please tell me what about, **cephx** support?

**Comment by ketor** [comment]
@pivusan No support of cephx yet. I am merging 10.2 from upstream to ceph-dokan. After this work, I will write the cephx support of ceph-dokan.
Please just wait a few days.

**Comment by pivusan** [comment]
Thanks for your work!

**Comment by jthiyagu** [comment]
Please Include me as well . Awaiting for cephx support in ceph-dokan.

**Comment by BloodBlight** [comment]
Is this project dead?

**Comment by jmzoda** [comment]
Who knows?
________________________________
De : BloodBlight <notifications@github.com>
Envoyé : dimanche 14 janvier 2018 21:10
À : ketor/ceph-dokan
Cc : Subscribed
Objet : Re: [ketor/ceph-dokan] No cephx support (#5)


Is this project dead?
