### ISSUE TITLE
direct IO support for ceph-dokan

### ISSUE THREAD

**Issue by shenyan1** [ketor/ceph-dokan#7]
Does ceph-dokan support direct IO？ I find no codes, either in dokan or ceph-dokan. The I/O performance doesn't change much when I disable direct io or enable direct io.

**Comment by ketor** [comment]
If you set client_oc = False in your ceph.conf, ceph-dokan is always using direct io.
Or ceph-dokan will I/O with cache.
Dokan does not support direct io ,so ceph-dokan cannot do anything for this.

**Comment by shenyan1** [comment]
thx for your help!
