### ISSUE TITLE
broken links to mingw

### ISSUE THREAD

**Issue by chipitsine** [ketor/ceph-dokan#9]
http://ceph.com/misc/MinGW-20150115.zip is 404

**Comment by ketor** [comment]
Thanks! Good catch! I would ask Sage for help fix this.

**Comment by ketor** [comment]
@chipitsine Please download MinGW zip file in https://www.dropbox.com/s/i72wyymzo0ets2s/MinGW-20151112.zip?dl=0 .

Sorry for late reply. I updated the README.md, you may need to look at it.

If you have problems, please let me know.
